/**
 * Type mapping tables for each source→target dialect pair.
 * Used to render unique, crawlable content on every tool page.
 *
 * Keys match the route slug pattern: `${sourceId}-to-${targetId}`
 */

export interface TypeRow {
  sourceType: string;
  targetType: string;
  notes?: string;
}

// ─── Generate routes: SQL dialect → code output ─────────────────────────────

export const generateMappings: Record<string, TypeRow[]> = {

  // ── PostgreSQL → * ─────────────────────────────────────────────────────────

  'postgres-to-typescript': [
    { sourceType: 'SERIAL / SMALLSERIAL', targetType: 'number', notes: 'Auto-increment PK; JS always returns number' },
    { sourceType: 'BIGSERIAL', targetType: 'number', notes: 'Use bigint for values exceeding 2⁵³' },
    { sourceType: 'INTEGER / INT / INT4', targetType: 'number' },
    { sourceType: 'BIGINT / INT8', targetType: 'number', notes: 'Beware precision loss for very large values' },
    { sourceType: 'SMALLINT / INT2', targetType: 'number' },
    { sourceType: 'NUMERIC / DECIMAL(p,s)', targetType: 'number', notes: 'Floating-point representation; use string for exact accounting' },
    { sourceType: 'REAL / FLOAT4', targetType: 'number' },
    { sourceType: 'DOUBLE PRECISION / FLOAT8', targetType: 'number' },
    { sourceType: 'VARCHAR(n) / CHARACTER VARYING', targetType: 'string' },
    { sourceType: 'TEXT', targetType: 'string', notes: 'Unlimited length string' },
    { sourceType: 'CHAR(n) / CHARACTER', targetType: 'string', notes: 'Fixed-length; padded with spaces in DB' },
    { sourceType: 'BOOLEAN / BOOL', targetType: 'boolean' },
    { sourceType: 'TIMESTAMP / TIMESTAMP WITH TIME ZONE', targetType: 'Date', notes: 'APIs typically return ISO 8601 string; parse with new Date()' },
    { sourceType: 'DATE', targetType: 'string', notes: 'Returns YYYY-MM-DD string; use Date only if parsing' },
    { sourceType: 'TIME', targetType: 'string', notes: 'Returns HH:MM:SS string' },
    { sourceType: 'UUID', targetType: 'string', notes: 'Generate with crypto.randomUUID()' },
    { sourceType: 'JSONB / JSON', targetType: 'Record<string, unknown>', notes: 'Define a typed interface for known shapes' },
    { sourceType: 'BYTEA', targetType: 'Buffer', notes: 'Node.js Buffer or Uint8Array in browser' },
    { sourceType: 'ARRAY (e.g. TEXT[])', targetType: 'string[]', notes: 'Typed array; replace with element type' },
    { sourceType: 'NOT NULL column', targetType: 'field: Type', notes: 'Required, non-optional property' },
    { sourceType: 'NULL / nullable column', targetType: 'field?: Type', notes: 'Optional property (or Type | null)' },
  ],

  'postgres-to-csharp-poco': [
    { sourceType: 'SERIAL / SMALLSERIAL', targetType: 'int', notes: '[Key] [DatabaseGenerated(DatabaseGeneratedOption.Identity)]' },
    { sourceType: 'BIGSERIAL', targetType: 'long', notes: '[Key] [DatabaseGenerated(DatabaseGeneratedOption.Identity)]' },
    { sourceType: 'INTEGER / INT / INT4', targetType: 'int' },
    { sourceType: 'BIGINT / INT8', targetType: 'long' },
    { sourceType: 'SMALLINT / INT2', targetType: 'short' },
    { sourceType: 'NUMERIC / DECIMAL(p,s)', targetType: 'decimal', notes: 'Exact; use for money fields' },
    { sourceType: 'REAL / FLOAT4', targetType: 'float' },
    { sourceType: 'DOUBLE PRECISION / FLOAT8', targetType: 'double' },
    { sourceType: 'VARCHAR(n)', targetType: 'string', notes: '[MaxLength(n)] attribute recommended' },
    { sourceType: 'TEXT', targetType: 'string' },
    { sourceType: 'CHAR(n)', targetType: 'string', notes: '[StringLength(n)] for exact length' },
    { sourceType: 'BOOLEAN / BOOL', targetType: 'bool' },
    { sourceType: 'TIMESTAMP', targetType: 'DateTime' },
    { sourceType: 'TIMESTAMP WITH TIME ZONE', targetType: 'DateTimeOffset', notes: 'Preserves timezone offset' },
    { sourceType: 'DATE', targetType: 'DateOnly', notes: '.NET 6+; use DateTime for older targets' },
    { sourceType: 'TIME', targetType: 'TimeOnly', notes: '.NET 6+; use TimeSpan for older targets' },
    { sourceType: 'UUID', targetType: 'Guid' },
    { sourceType: 'JSONB / JSON', targetType: 'string', notes: 'Store as string or use [Column(TypeName="jsonb")]' },
    { sourceType: 'BYTEA', targetType: 'byte[]' },
    { sourceType: 'NOT NULL column', targetType: 'Type Field', notes: '[Required] attribute; non-nullable value type' },
    { sourceType: 'NULL / nullable column', targetType: 'Type? Field', notes: 'Nullable value type or nullable reference type' },
  ],

  'postgres-to-python-dataclass': [
    { sourceType: 'SERIAL / SMALLSERIAL', targetType: 'int', notes: 'field(default=None) for auto-generated PK' },
    { sourceType: 'BIGSERIAL', targetType: 'int', notes: 'Python int is arbitrary precision' },
    { sourceType: 'INTEGER / INT / INT4', targetType: 'int' },
    { sourceType: 'BIGINT / INT8', targetType: 'int' },
    { sourceType: 'SMALLINT / INT2', targetType: 'int' },
    { sourceType: 'NUMERIC / DECIMAL(p,s)', targetType: 'Decimal', notes: 'Import from decimal module for exact arithmetic' },
    { sourceType: 'REAL / FLOAT4', targetType: 'float' },
    { sourceType: 'DOUBLE PRECISION / FLOAT8', targetType: 'float' },
    { sourceType: 'VARCHAR(n) / TEXT', targetType: 'str' },
    { sourceType: 'CHAR(n)', targetType: 'str' },
    { sourceType: 'BOOLEAN / BOOL', targetType: 'bool' },
    { sourceType: 'TIMESTAMP', targetType: 'datetime', notes: 'from datetime import datetime' },
    { sourceType: 'TIMESTAMP WITH TIME ZONE', targetType: 'datetime', notes: 'Use timezone-aware: datetime.timezone.utc' },
    { sourceType: 'DATE', targetType: 'date', notes: 'from datetime import date' },
    { sourceType: 'TIME', targetType: 'time', notes: 'from datetime import time' },
    { sourceType: 'UUID', targetType: 'UUID', notes: 'from uuid import UUID' },
    { sourceType: 'JSONB / JSON', targetType: 'dict[str, Any]', notes: 'from typing import Any; or define TypedDict' },
    { sourceType: 'BYTEA', targetType: 'bytes' },
    { sourceType: 'NOT NULL column', targetType: 'field: Type', notes: 'No default; required at construction' },
    { sourceType: 'NULL / nullable column', targetType: 'field: Optional[Type] = None', notes: 'from typing import Optional' },
  ],

  'postgres-to-java-entity': [
    { sourceType: 'SERIAL / SMALLSERIAL', targetType: 'Integer', notes: '@Id @GeneratedValue(strategy=IDENTITY)' },
    { sourceType: 'BIGSERIAL', targetType: 'Long', notes: '@Id @GeneratedValue(strategy=IDENTITY)' },
    { sourceType: 'INTEGER / INT / INT4', targetType: 'Integer' },
    { sourceType: 'BIGINT / INT8', targetType: 'Long' },
    { sourceType: 'SMALLINT / INT2', targetType: 'Short' },
    { sourceType: 'NUMERIC / DECIMAL(p,s)', targetType: 'BigDecimal', notes: '@Column(precision=p, scale=s)' },
    { sourceType: 'REAL / FLOAT4', targetType: 'Float' },
    { sourceType: 'DOUBLE PRECISION / FLOAT8', targetType: 'Double' },
    { sourceType: 'VARCHAR(n)', targetType: 'String', notes: '@Column(length=n)' },
    { sourceType: 'TEXT', targetType: 'String', notes: '@Column(columnDefinition="TEXT")' },
    { sourceType: 'CHAR(n)', targetType: 'String', notes: '@Column(columnDefinition="CHAR(n)")' },
    { sourceType: 'BOOLEAN / BOOL', targetType: 'Boolean' },
    { sourceType: 'TIMESTAMP', targetType: 'LocalDateTime', notes: 'java.time.LocalDateTime' },
    { sourceType: 'TIMESTAMP WITH TIME ZONE', targetType: 'OffsetDateTime', notes: 'java.time.OffsetDateTime' },
    { sourceType: 'DATE', targetType: 'LocalDate', notes: 'java.time.LocalDate' },
    { sourceType: 'TIME', targetType: 'LocalTime', notes: 'java.time.LocalTime' },
    { sourceType: 'UUID', targetType: 'UUID', notes: 'java.util.UUID; @Column(columnDefinition="uuid")' },
    { sourceType: 'JSONB / JSON', targetType: 'String', notes: 'Store as String or use custom converter' },
    { sourceType: 'BYTEA', targetType: 'byte[]' },
    { sourceType: 'NOT NULL column', targetType: 'Type field', notes: '@Column(nullable=false)' },
    { sourceType: 'NULL / nullable column', targetType: 'Type field', notes: '@Column(nullable=true) — default' },
  ],

  'postgres-to-go-struct': [
    { sourceType: 'SERIAL / SMALLSERIAL', targetType: 'int', notes: '`gorm:"primaryKey;autoIncrement"`' },
    { sourceType: 'BIGSERIAL', targetType: 'int64', notes: '`gorm:"primaryKey;autoIncrement"`' },
    { sourceType: 'INTEGER / INT / INT4', targetType: 'int' },
    { sourceType: 'BIGINT / INT8', targetType: 'int64' },
    { sourceType: 'SMALLINT / INT2', targetType: 'int16' },
    { sourceType: 'NUMERIC / DECIMAL(p,s)', targetType: 'float64', notes: 'Use decimal.Decimal (shopspring/decimal) for exact values' },
    { sourceType: 'REAL / FLOAT4', targetType: 'float32' },
    { sourceType: 'DOUBLE PRECISION / FLOAT8', targetType: 'float64' },
    { sourceType: 'VARCHAR(n) / TEXT', targetType: 'string' },
    { sourceType: 'CHAR(n)', targetType: 'string' },
    { sourceType: 'BOOLEAN / BOOL', targetType: 'bool' },
    { sourceType: 'TIMESTAMP', targetType: 'time.Time', notes: 'import "time"' },
    { sourceType: 'TIMESTAMP WITH TIME ZONE', targetType: 'time.Time', notes: 'Go time.Time is always timezone-aware' },
    { sourceType: 'DATE', targetType: 'time.Time', notes: 'Consider civil.Date (go-chrono/civil)' },
    { sourceType: 'UUID', targetType: 'string', notes: 'Or uuid.UUID from google/uuid package' },
    { sourceType: 'JSONB / JSON', targetType: 'json.RawMessage', notes: 'Or define typed struct; import encoding/json' },
    { sourceType: 'BYTEA', targetType: '[]byte' },
    { sourceType: 'NOT NULL column', targetType: 'field Type', notes: 'Non-pointer; required value' },
    { sourceType: 'NULL / nullable column', targetType: 'field *Type', notes: 'Pointer type allows nil (null)' },
  ],

  'postgres-to-mock-json': [
    { sourceType: 'SERIAL / INTEGER', targetType: 'Number (integer)', notes: 'e.g. 1, 42, 1024' },
    { sourceType: 'BIGINT / BIGSERIAL', targetType: 'Number (integer)', notes: 'e.g. 8291048302' },
    { sourceType: 'VARCHAR(n) — name columns', targetType: 'Faker name string', notes: 'e.g. "John Smith"' },
    { sourceType: 'VARCHAR(n) — email columns', targetType: 'Faker email string', notes: 'e.g. "user@example.com"' },
    { sourceType: 'TEXT', targetType: 'Faker lorem sentence', notes: 'Contextually chosen by column name' },
    { sourceType: 'BOOLEAN', targetType: 'true / false', notes: 'Random boolean' },
    { sourceType: 'TIMESTAMP', targetType: 'ISO 8601 string', notes: 'e.g. "2024-03-15T09:41:22.000Z"' },
    { sourceType: 'DATE', targetType: 'Date string', notes: 'e.g. "2024-03-15"' },
    { sourceType: 'DECIMAL / NUMERIC', targetType: 'Number (float)', notes: 'e.g. 1234.56' },
    { sourceType: 'UUID', targetType: 'UUID v4 string', notes: 'e.g. "a1b2c3d4-..."' },
    { sourceType: 'JSONB / JSON', targetType: 'Nested JSON object', notes: 'Contextually generated key-value pairs' },
    { sourceType: 'NOT NULL', targetType: 'Always present', notes: 'Never null in mock output' },
    { sourceType: 'NULL / nullable', targetType: 'Occasionally null', notes: '~20% chance of null for realism' },
  ],

  'postgres-to-sql-inserts': [
    { sourceType: 'SERIAL / INT auto PK', targetType: 'INTEGER literal', notes: 'e.g. 1, 2, 3 — sequential values' },
    { sourceType: 'VARCHAR(n) / TEXT', targetType: "String literal", notes: "e.g. 'John Smith'" },
    { sourceType: 'BOOLEAN', targetType: 'TRUE / FALSE', notes: 'PostgreSQL boolean literals' },
    { sourceType: 'TIMESTAMP', targetType: "Timestamp literal", notes: "e.g. '2024-03-15 09:41:22'" },
    { sourceType: 'DATE', targetType: "Date literal", notes: "e.g. '2024-03-15'" },
    { sourceType: 'DECIMAL / NUMERIC', targetType: 'Numeric literal', notes: 'e.g. 1234.56' },
    { sourceType: 'UUID', targetType: 'UUID string', notes: "e.g. 'a1b2c3d4-...'" },
    { sourceType: 'JSONB / JSON', targetType: 'JSON string literal', notes: "e.g. '{\"key\": \"value\"}'" },
    { sourceType: 'BYTEA', targetType: "Hex literal", notes: "e.g. '\\\\x48656c6c6f'" },
    { sourceType: 'NULL value', targetType: 'NULL', notes: 'SQL NULL literal' },
  ],

  // ── MySQL → * ──────────────────────────────────────────────────────────────

  'mysql-to-typescript': [
    { sourceType: 'INT AUTO_INCREMENT', targetType: 'number', notes: 'Auto-increment PK' },
    { sourceType: 'BIGINT AUTO_INCREMENT', targetType: 'number', notes: 'Use bigint for very large IDs' },
    { sourceType: 'INT / INTEGER', targetType: 'number' },
    { sourceType: 'BIGINT', targetType: 'number' },
    { sourceType: 'TINYINT(1)', targetType: 'boolean', notes: 'MySQL boolean convention; 0=false, 1=true' },
    { sourceType: 'TINYINT / SMALLINT / MEDIUMINT', targetType: 'number' },
    { sourceType: 'FLOAT', targetType: 'number' },
    { sourceType: 'DOUBLE / DOUBLE PRECISION', targetType: 'number' },
    { sourceType: 'DECIMAL(p,s)', targetType: 'number', notes: 'Use string for exact currency values' },
    { sourceType: 'VARCHAR(n)', targetType: 'string' },
    { sourceType: 'TEXT / TINYTEXT / MEDIUMTEXT / LONGTEXT', targetType: 'string' },
    { sourceType: 'CHAR(n)', targetType: 'string' },
    { sourceType: 'DATETIME', targetType: 'Date', notes: 'No timezone; local server time' },
    { sourceType: 'TIMESTAMP', targetType: 'Date', notes: 'UTC-stored; auto-converts on SELECT' },
    { sourceType: 'DATE', targetType: 'string', notes: 'Returns YYYY-MM-DD string' },
    { sourceType: 'TIME', targetType: 'string', notes: 'Returns HH:MM:SS string' },
    { sourceType: 'JSON', targetType: 'Record<string, unknown>', notes: 'MySQL 5.7+; define typed interface' },
    { sourceType: 'BLOB / LONGBLOB', targetType: 'Buffer', notes: 'Binary data as Node.js Buffer' },
    { sourceType: 'ENUM(\'a\',\'b\')', targetType: "'a' | 'b'", notes: 'TypeScript string literal union' },
    { sourceType: 'NULL column', targetType: 'field?: Type', notes: 'Optional property' },
  ],

  'mysql-to-csharp-poco': [
    { sourceType: 'INT AUTO_INCREMENT', targetType: 'int', notes: '[Key] [DatabaseGenerated(DatabaseGeneratedOption.Identity)]' },
    { sourceType: 'BIGINT AUTO_INCREMENT', targetType: 'long', notes: '[Key] [DatabaseGenerated(DatabaseGeneratedOption.Identity)]' },
    { sourceType: 'INT / INTEGER', targetType: 'int' },
    { sourceType: 'BIGINT', targetType: 'long' },
    { sourceType: 'TINYINT(1)', targetType: 'bool', notes: 'MySQL boolean; EF Core maps automatically' },
    { sourceType: 'TINYINT / SMALLINT', targetType: 'short' },
    { sourceType: 'MEDIUMINT', targetType: 'int' },
    { sourceType: 'FLOAT', targetType: 'float' },
    { sourceType: 'DOUBLE', targetType: 'double' },
    { sourceType: 'DECIMAL(p,s)', targetType: 'decimal', notes: 'Exact; [Column(TypeName="decimal(p,s)")]' },
    { sourceType: 'VARCHAR(n)', targetType: 'string', notes: '[MaxLength(n)]' },
    { sourceType: 'TEXT / LONGTEXT', targetType: 'string' },
    { sourceType: 'DATETIME', targetType: 'DateTime', notes: 'No timezone offset stored' },
    { sourceType: 'TIMESTAMP', targetType: 'DateTime', notes: 'UTC; mapped from TIMESTAMP column' },
    { sourceType: 'DATE', targetType: 'DateOnly', notes: '.NET 6+; use DateTime for earlier' },
    { sourceType: 'JSON', targetType: 'string', notes: 'Store as JSON string or use custom converter' },
    { sourceType: 'BLOB', targetType: 'byte[]' },
    { sourceType: 'ENUM', targetType: 'string', notes: 'Or define C# enum and use converter' },
    { sourceType: 'NULL column', targetType: 'Type? Field', notes: 'Nullable value or reference type' },
  ],

  'mysql-to-python-dataclass': [
    { sourceType: 'INT AUTO_INCREMENT', targetType: 'int', notes: 'field(default=None) for DB-generated PK' },
    { sourceType: 'BIGINT', targetType: 'int', notes: 'Python int is arbitrary precision' },
    { sourceType: 'INT / INTEGER', targetType: 'int' },
    { sourceType: 'TINYINT(1)', targetType: 'bool', notes: 'Map 0/1 to Python bool' },
    { sourceType: 'FLOAT', targetType: 'float' },
    { sourceType: 'DOUBLE', targetType: 'float' },
    { sourceType: 'DECIMAL(p,s)', targetType: 'Decimal', notes: 'from decimal import Decimal' },
    { sourceType: 'VARCHAR(n) / TEXT', targetType: 'str' },
    { sourceType: 'DATETIME', targetType: 'datetime', notes: 'from datetime import datetime; no tzinfo' },
    { sourceType: 'TIMESTAMP', targetType: 'datetime', notes: 'Treat as UTC; datetime.timezone.utc' },
    { sourceType: 'DATE', targetType: 'date', notes: 'from datetime import date' },
    { sourceType: 'JSON', targetType: 'dict[str, Any]', notes: 'from typing import Any; or use TypedDict' },
    { sourceType: 'BLOB', targetType: 'bytes' },
    { sourceType: 'ENUM', targetType: 'str', notes: 'Or use Python Enum class' },
    { sourceType: 'NULL column', targetType: 'Optional[Type] = None', notes: 'from typing import Optional' },
  ],

  'mysql-to-java-entity': [
    { sourceType: 'INT AUTO_INCREMENT', targetType: 'Integer', notes: '@Id @GeneratedValue(strategy=IDENTITY)' },
    { sourceType: 'BIGINT AUTO_INCREMENT', targetType: 'Long', notes: '@Id @GeneratedValue(strategy=IDENTITY)' },
    { sourceType: 'INT / INTEGER', targetType: 'Integer' },
    { sourceType: 'BIGINT', targetType: 'Long' },
    { sourceType: 'TINYINT(1)', targetType: 'Boolean', notes: 'MySQL boolean' },
    { sourceType: 'FLOAT', targetType: 'Float' },
    { sourceType: 'DOUBLE', targetType: 'Double' },
    { sourceType: 'DECIMAL(p,s)', targetType: 'BigDecimal', notes: '@Column(precision=p, scale=s)' },
    { sourceType: 'VARCHAR(n)', targetType: 'String', notes: '@Column(length=n)' },
    { sourceType: 'TEXT / LONGTEXT', targetType: 'String', notes: '@Column(columnDefinition="TEXT")' },
    { sourceType: 'DATETIME', targetType: 'LocalDateTime', notes: 'java.time.LocalDateTime' },
    { sourceType: 'TIMESTAMP', targetType: 'LocalDateTime', notes: 'UTC-stored' },
    { sourceType: 'DATE', targetType: 'LocalDate', notes: 'java.time.LocalDate' },
    { sourceType: 'JSON', targetType: 'String', notes: '@Column(columnDefinition="JSON") or custom converter' },
    { sourceType: 'BLOB', targetType: 'byte[]', notes: '@Lob annotation' },
    { sourceType: 'ENUM', targetType: '@Enumerated(EnumType.STRING) MyEnum', notes: 'Define Java Enum to match MySQL ENUM values' },
    { sourceType: 'NULL column', targetType: 'Type field', notes: '@Column(nullable=true)' },
  ],

  'mysql-to-go-struct': [
    { sourceType: 'INT AUTO_INCREMENT', targetType: 'int', notes: '`gorm:"primaryKey;autoIncrement"`' },
    { sourceType: 'BIGINT AUTO_INCREMENT', targetType: 'int64', notes: '`gorm:"primaryKey;autoIncrement"`' },
    { sourceType: 'INT / INTEGER', targetType: 'int' },
    { sourceType: 'BIGINT', targetType: 'int64' },
    { sourceType: 'TINYINT(1)', targetType: 'bool' },
    { sourceType: 'FLOAT', targetType: 'float32' },
    { sourceType: 'DOUBLE', targetType: 'float64' },
    { sourceType: 'DECIMAL(p,s)', targetType: 'float64', notes: 'Use shopspring/decimal for exact arithmetic' },
    { sourceType: 'VARCHAR(n) / TEXT', targetType: 'string' },
    { sourceType: 'DATETIME', targetType: 'time.Time', notes: 'import "time"; no timezone stored' },
    { sourceType: 'TIMESTAMP', targetType: 'time.Time', notes: 'UTC-stored; Go treats as UTC' },
    { sourceType: 'DATE', targetType: 'time.Time', notes: 'Time portion will be zero' },
    { sourceType: 'JSON', targetType: 'json.RawMessage', notes: 'import encoding/json; or typed struct' },
    { sourceType: 'BLOB', targetType: '[]byte' },
    { sourceType: 'ENUM', targetType: 'string', notes: 'Or define typed string alias with constants' },
    { sourceType: 'NULL column', targetType: '*Type', notes: 'Pointer type allows nil' },
  ],

  'mysql-to-mock-json': [
    { sourceType: 'INT AUTO_INCREMENT', targetType: 'Number (integer)', notes: 'Sequential: 1, 2, 3...' },
    { sourceType: 'VARCHAR(n) — name', targetType: 'Faker full name', notes: 'e.g. "Jane Doe"' },
    { sourceType: 'VARCHAR(n) — email', targetType: 'Faker email', notes: 'e.g. "jane.doe@example.com"' },
    { sourceType: 'TINYINT(1)', targetType: 'true / false', notes: 'Random boolean' },
    { sourceType: 'DATETIME / TIMESTAMP', targetType: 'ISO 8601 string', notes: 'e.g. "2024-03-15T09:41:22.000Z"' },
    { sourceType: 'DECIMAL(p,s)', targetType: 'Number (float)', notes: 'Rounded to s decimal places' },
    { sourceType: 'TEXT', targetType: 'Faker lorem paragraph', notes: 'Context-aware lorem text' },
    { sourceType: 'JSON', targetType: 'Nested JSON object', notes: 'Generated from column name context' },
    { sourceType: 'NULL column', targetType: 'Occasionally null', notes: '~20% chance for nullable columns' },
  ],

  'mysql-to-sql-inserts': [
    { sourceType: 'INT AUTO_INCREMENT', targetType: 'INTEGER literal', notes: 'Sequential: 1, 2, 3' },
    { sourceType: 'VARCHAR(n) / TEXT', targetType: "String literal", notes: "Single-quoted: 'value'" },
    { sourceType: 'TINYINT(1)', targetType: '0 / 1', notes: 'MySQL boolean convention' },
    { sourceType: 'DATETIME / TIMESTAMP', targetType: "Datetime literal", notes: "'2024-03-15 09:41:22'" },
    { sourceType: 'DECIMAL(p,s)', targetType: 'Numeric literal', notes: '1234.56' },
    { sourceType: 'JSON', targetType: 'JSON string literal', notes: "'{\"key\": \"value\"}'" },
    { sourceType: 'NULL', targetType: 'NULL', notes: 'SQL NULL literal' },
  ],

  // ── SQLite → * ─────────────────────────────────────────────────────────────

  'sqlite-to-typescript': [
    { sourceType: 'INTEGER PRIMARY KEY', targetType: 'number', notes: 'SQLite rowid alias; auto-increments' },
    { sourceType: 'INTEGER', targetType: 'number', notes: 'SQLite stores all integers as 1–8 byte signed int' },
    { sourceType: 'REAL', targetType: 'number', notes: '8-byte IEEE floating point' },
    { sourceType: 'TEXT', targetType: 'string', notes: 'UTF-8 or UTF-16; unlimited length' },
    { sourceType: 'BLOB', targetType: 'Uint8Array', notes: 'Binary data; Buffer in Node.js' },
    { sourceType: 'NUMERIC affinity', targetType: 'number', notes: 'SQLite coerces to INTEGER or REAL' },
    { sourceType: 'BOOLEAN (stored as INTEGER)', targetType: 'boolean', notes: 'SQLite stores 0/1; cast in code' },
    { sourceType: 'DATE / DATETIME (stored as TEXT)', targetType: 'string', notes: 'SQLite has no date type; parse with new Date()' },
    { sourceType: 'JSON (stored as TEXT)', targetType: 'Record<string, unknown>', notes: 'Parse with JSON.parse(); no native JSON type' },
    { sourceType: 'NULL column', targetType: 'field?: Type', notes: 'SQLite allows NULL in any column by default' },
  ],

  'sqlite-to-csharp-poco': [
    { sourceType: 'INTEGER PRIMARY KEY', targetType: 'long', notes: '[Key] SQLite rowid; 64-bit signed integer' },
    { sourceType: 'INTEGER', targetType: 'long', notes: 'SQLite INTEGER is always 64-bit' },
    { sourceType: 'REAL', targetType: 'double', notes: '8-byte float' },
    { sourceType: 'TEXT', targetType: 'string' },
    { sourceType: 'BLOB', targetType: 'byte[]' },
    { sourceType: 'BOOLEAN (INTEGER 0/1)', targetType: 'bool', notes: 'Microsoft.Data.Sqlite maps automatically' },
    { sourceType: 'DATE / DATETIME (TEXT)', targetType: 'DateTime', notes: 'SQLite stores as ISO text; parsed by driver' },
    { sourceType: 'NULL column', targetType: 'Type? Field', notes: 'Nullable; any SQLite column can be NULL' },
  ],

  'sqlite-to-python-dataclass': [
    { sourceType: 'INTEGER PRIMARY KEY', targetType: 'int', notes: 'SQLite ROWID alias; auto-assigned' },
    { sourceType: 'INTEGER', targetType: 'int', notes: 'Python int is arbitrary precision; no overflow' },
    { sourceType: 'REAL', targetType: 'float', notes: '8-byte double precision' },
    { sourceType: 'TEXT', targetType: 'str' },
    { sourceType: 'BLOB', targetType: 'bytes' },
    { sourceType: 'BOOLEAN (stored as INTEGER)', targetType: 'bool', notes: 'Cast: bool(row["field"])' },
    { sourceType: 'DATE (stored as TEXT)', targetType: 'date', notes: 'date.fromisoformat(row["field"])' },
    { sourceType: 'DATETIME (stored as TEXT)', targetType: 'datetime', notes: 'datetime.fromisoformat(row["field"])' },
    { sourceType: 'NULL column', targetType: 'Optional[Type] = None' },
  ],

  'sqlite-to-java-entity': [
    { sourceType: 'INTEGER PRIMARY KEY', targetType: 'Long', notes: '@Id; SQLite rowid is 64-bit' },
    { sourceType: 'INTEGER', targetType: 'Long', notes: 'SQLite INTEGER is always int64' },
    { sourceType: 'REAL', targetType: 'Double' },
    { sourceType: 'TEXT', targetType: 'String' },
    { sourceType: 'BLOB', targetType: 'byte[]', notes: '@Lob' },
    { sourceType: 'BOOLEAN (0/1)', targetType: 'Boolean', notes: '@Column(columnDefinition="INTEGER")' },
    { sourceType: 'DATE / DATETIME (TEXT)', targetType: 'LocalDateTime', notes: 'Use @Convert with custom AttributeConverter' },
    { sourceType: 'NULL column', targetType: 'Type field', notes: '@Column(nullable=true)' },
  ],

  'sqlite-to-go-struct': [
    { sourceType: 'INTEGER PRIMARY KEY', targetType: 'int64', notes: 'SQLite rowid; 64-bit signed integer' },
    { sourceType: 'INTEGER', targetType: 'int64', notes: 'Always 64-bit in SQLite' },
    { sourceType: 'REAL', targetType: 'float64' },
    { sourceType: 'TEXT', targetType: 'string' },
    { sourceType: 'BLOB', targetType: '[]byte' },
    { sourceType: 'BOOLEAN (INTEGER)', targetType: 'bool', notes: 'Database/sql driver converts automatically' },
    { sourceType: 'DATE / DATETIME (TEXT)', targetType: 'time.Time', notes: 'Use time.Parse with RFC3339 format' },
    { sourceType: 'NULL column', targetType: '*Type', notes: 'Or sql.NullString / sql.NullInt64' },
  ],

  'sqlite-to-mock-json': [
    { sourceType: 'INTEGER PRIMARY KEY', targetType: 'Number (integer)', notes: 'Sequential integers' },
    { sourceType: 'INTEGER', targetType: 'Number (integer)' },
    { sourceType: 'REAL', targetType: 'Number (float)', notes: 'e.g. 12.34' },
    { sourceType: 'TEXT', targetType: 'Faker context-aware string', notes: 'Name, email, or lorem based on column name' },
    { sourceType: 'BLOB', targetType: 'Base64 string', notes: 'Represented as base64 in JSON' },
    { sourceType: 'BOOLEAN (0/1)', targetType: 'true / false' },
    { sourceType: 'DATE / DATETIME (TEXT)', targetType: 'ISO 8601 string' },
    { sourceType: 'NULL column', targetType: 'Occasionally null', notes: '~20% chance' },
  ],

  'sqlite-to-sql-inserts': [
    { sourceType: 'INTEGER PRIMARY KEY', targetType: 'INTEGER literal', notes: 'SQLite auto-assigns if omitted' },
    { sourceType: 'INTEGER', targetType: 'INTEGER literal' },
    { sourceType: 'REAL', targetType: 'REAL literal', notes: 'e.g. 12.34' },
    { sourceType: 'TEXT', targetType: "TEXT literal", notes: "Single-quoted: 'value'" },
    { sourceType: 'BLOB', targetType: "X'hex' literal", notes: "e.g. X'48656c6c6f'" },
    { sourceType: 'NULL column', targetType: 'NULL' },
  ],

  // ── SQL Server → * ─────────────────────────────────────────────────────────

  'sql-server-to-typescript': [
    { sourceType: 'INT IDENTITY(1,1)', targetType: 'number', notes: 'Auto-increment PK' },
    { sourceType: 'BIGINT IDENTITY(1,1)', targetType: 'number', notes: 'Large auto-increment PK' },
    { sourceType: 'INT', targetType: 'number' },
    { sourceType: 'BIGINT', targetType: 'number', notes: 'Use bigint for values > 2^53' },
    { sourceType: 'SMALLINT / TINYINT', targetType: 'number' },
    { sourceType: 'FLOAT / REAL', targetType: 'number' },
    { sourceType: 'DECIMAL(p,s) / NUMERIC(p,s)', targetType: 'number', notes: 'Use string for exact financials' },
    { sourceType: 'MONEY / SMALLMONEY', targetType: 'number', notes: 'Consider string for accounting precision' },
    { sourceType: 'VARCHAR(n) / NVARCHAR(n)', targetType: 'string', notes: 'NVARCHAR is Unicode; both map to string' },
    { sourceType: 'TEXT / NTEXT', targetType: 'string', notes: 'Deprecated; prefer NVARCHAR(MAX)' },
    { sourceType: 'NVARCHAR(MAX)', targetType: 'string' },
    { sourceType: 'CHAR(n) / NCHAR(n)', targetType: 'string' },
    { sourceType: 'BIT', targetType: 'boolean', notes: 'SQL Server boolean type' },
    { sourceType: 'DATETIME / DATETIME2', targetType: 'Date', notes: 'DATETIME2 has higher precision' },
    { sourceType: 'DATETIMEOFFSET', targetType: 'Date', notes: 'Includes timezone; parse with Date.parse()' },
    { sourceType: 'DATE', targetType: 'string', notes: 'Returns YYYY-MM-DD' },
    { sourceType: 'TIME', targetType: 'string', notes: 'Returns HH:MM:SS.fff' },
    { sourceType: 'UNIQUEIDENTIFIER', targetType: 'string', notes: 'GUID/UUID format string' },
    { sourceType: 'VARBINARY(n) / IMAGE', targetType: 'Buffer', notes: 'Binary data as Node.js Buffer' },
    { sourceType: 'NULL column', targetType: 'field?: Type' },
  ],

  'sql-server-to-csharp-poco': [
    { sourceType: 'INT IDENTITY(1,1)', targetType: 'int', notes: '[Key] [DatabaseGenerated(DatabaseGeneratedOption.Identity)]' },
    { sourceType: 'BIGINT IDENTITY(1,1)', targetType: 'long', notes: '[Key] [DatabaseGenerated(DatabaseGeneratedOption.Identity)]' },
    { sourceType: 'INT', targetType: 'int' },
    { sourceType: 'BIGINT', targetType: 'long' },
    { sourceType: 'SMALLINT', targetType: 'short' },
    { sourceType: 'TINYINT', targetType: 'byte' },
    { sourceType: 'FLOAT', targetType: 'double' },
    { sourceType: 'REAL', targetType: 'float' },
    { sourceType: 'DECIMAL(p,s) / NUMERIC(p,s)', targetType: 'decimal' },
    { sourceType: 'MONEY / SMALLMONEY', targetType: 'decimal', notes: '[Column(TypeName="money")]' },
    { sourceType: 'VARCHAR(n) / NVARCHAR(n)', targetType: 'string', notes: '[MaxLength(n)]' },
    { sourceType: 'NVARCHAR(MAX)', targetType: 'string' },
    { sourceType: 'BIT', targetType: 'bool' },
    { sourceType: 'DATETIME', targetType: 'DateTime' },
    { sourceType: 'DATETIME2', targetType: 'DateTime', notes: '[Column(TypeName="datetime2")]' },
    { sourceType: 'DATETIMEOFFSET', targetType: 'DateTimeOffset' },
    { sourceType: 'DATE', targetType: 'DateOnly', notes: '.NET 6+' },
    { sourceType: 'TIME', targetType: 'TimeOnly', notes: '.NET 6+' },
    { sourceType: 'UNIQUEIDENTIFIER', targetType: 'Guid' },
    { sourceType: 'VARBINARY(n) / IMAGE', targetType: 'byte[]' },
    { sourceType: 'NULL column', targetType: 'Type? Field' },
  ],

  'sql-server-to-python-dataclass': [
    { sourceType: 'INT IDENTITY(1,1)', targetType: 'int', notes: 'field(default=None) for DB-generated PK' },
    { sourceType: 'INT', targetType: 'int' },
    { sourceType: 'BIGINT', targetType: 'int' },
    { sourceType: 'FLOAT / REAL', targetType: 'float' },
    { sourceType: 'DECIMAL / NUMERIC', targetType: 'Decimal', notes: 'from decimal import Decimal' },
    { sourceType: 'MONEY / SMALLMONEY', targetType: 'Decimal', notes: 'Exact decimal arithmetic' },
    { sourceType: 'VARCHAR / NVARCHAR', targetType: 'str' },
    { sourceType: 'BIT', targetType: 'bool' },
    { sourceType: 'DATETIME / DATETIME2', targetType: 'datetime', notes: 'from datetime import datetime' },
    { sourceType: 'DATETIMEOFFSET', targetType: 'datetime', notes: 'Use timezone-aware datetime' },
    { sourceType: 'DATE', targetType: 'date', notes: 'from datetime import date' },
    { sourceType: 'UNIQUEIDENTIFIER', targetType: 'UUID', notes: 'from uuid import UUID' },
    { sourceType: 'VARBINARY / IMAGE', targetType: 'bytes' },
    { sourceType: 'NULL column', targetType: 'Optional[Type] = None' },
  ],

  'sql-server-to-java-entity': [
    { sourceType: 'INT IDENTITY(1,1)', targetType: 'Integer', notes: '@Id @GeneratedValue(strategy=IDENTITY)' },
    { sourceType: 'BIGINT IDENTITY(1,1)', targetType: 'Long', notes: '@Id @GeneratedValue(strategy=IDENTITY)' },
    { sourceType: 'INT', targetType: 'Integer' },
    { sourceType: 'BIGINT', targetType: 'Long' },
    { sourceType: 'FLOAT', targetType: 'Double' },
    { sourceType: 'DECIMAL / NUMERIC', targetType: 'BigDecimal' },
    { sourceType: 'MONEY', targetType: 'BigDecimal', notes: '@Column(columnDefinition="money")' },
    { sourceType: 'VARCHAR(n) / NVARCHAR(n)', targetType: 'String', notes: '@Column(length=n)' },
    { sourceType: 'BIT', targetType: 'Boolean' },
    { sourceType: 'DATETIME / DATETIME2', targetType: 'LocalDateTime' },
    { sourceType: 'DATETIMEOFFSET', targetType: 'OffsetDateTime' },
    { sourceType: 'DATE', targetType: 'LocalDate' },
    { sourceType: 'UNIQUEIDENTIFIER', targetType: 'UUID', notes: 'java.util.UUID; @Column(columnDefinition="uniqueidentifier")' },
    { sourceType: 'VARBINARY', targetType: 'byte[]', notes: '@Lob' },
    { sourceType: 'NULL column', targetType: 'Type field', notes: '@Column(nullable=true)' },
  ],

  'sql-server-to-go-struct': [
    { sourceType: 'INT IDENTITY(1,1)', targetType: 'int', notes: '`gorm:"primaryKey;autoIncrement"`' },
    { sourceType: 'BIGINT IDENTITY(1,1)', targetType: 'int64' },
    { sourceType: 'INT', targetType: 'int' },
    { sourceType: 'BIGINT', targetType: 'int64' },
    { sourceType: 'SMALLINT', targetType: 'int16' },
    { sourceType: 'TINYINT', targetType: 'uint8' },
    { sourceType: 'FLOAT', targetType: 'float64' },
    { sourceType: 'DECIMAL / NUMERIC', targetType: 'float64', notes: 'Use shopspring/decimal for exact values' },
    { sourceType: 'MONEY', targetType: 'float64', notes: 'Or shopspring/decimal' },
    { sourceType: 'VARCHAR / NVARCHAR', targetType: 'string' },
    { sourceType: 'BIT', targetType: 'bool' },
    { sourceType: 'DATETIME / DATETIME2', targetType: 'time.Time' },
    { sourceType: 'DATETIMEOFFSET', targetType: 'time.Time', notes: 'Timezone preserved' },
    { sourceType: 'UNIQUEIDENTIFIER', targetType: 'string', notes: 'Or uuid.UUID from google/uuid' },
    { sourceType: 'VARBINARY', targetType: '[]byte' },
    { sourceType: 'NULL column', targetType: '*Type' },
  ],

  'sql-server-to-mock-json': [
    { sourceType: 'INT IDENTITY(1,1)', targetType: 'Number (integer)', notes: 'Sequential' },
    { sourceType: 'NVARCHAR(n) — name', targetType: 'Faker full name' },
    { sourceType: 'NVARCHAR(n) — email', targetType: 'Faker email' },
    { sourceType: 'BIT', targetType: 'true / false' },
    { sourceType: 'DATETIME / DATETIME2', targetType: 'ISO 8601 string' },
    { sourceType: 'DECIMAL / MONEY', targetType: 'Number (float, 2dp)', notes: 'e.g. 99.99' },
    { sourceType: 'UNIQUEIDENTIFIER', targetType: 'UUID v4 string' },
    { sourceType: 'NULL column', targetType: 'Occasionally null', notes: '~20% chance' },
  ],

  'sql-server-to-sql-inserts': [
    { sourceType: 'INT IDENTITY(1,1)', targetType: 'INTEGER literal', notes: 'Wrap in SET IDENTITY_INSERT ON/OFF' },
    { sourceType: 'NVARCHAR / VARCHAR', targetType: "N'string' literal", notes: "N prefix for Unicode: N'value'" },
    { sourceType: 'BIT', targetType: '0 / 1', notes: 'SQL Server boolean' },
    { sourceType: 'DATETIME', targetType: "'YYYY-MM-DD HH:MM:SS' literal" },
    { sourceType: 'UNIQUEIDENTIFIER', targetType: "NEWID() or 'xxxxxxxx-...' literal" },
    { sourceType: 'NULL', targetType: 'NULL' },
  ],

  // ── Oracle → * ─────────────────────────────────────────────────────────────

  'oracle-to-typescript': [
    { sourceType: 'NUMBER(p,0) / INTEGER', targetType: 'number' },
    { sourceType: 'NUMBER(p,s) / FLOAT', targetType: 'number', notes: 'Use string for exact financials (NUMBER is arbitrary precision)' },
    { sourceType: 'BINARY_FLOAT', targetType: 'number', notes: '32-bit IEEE float' },
    { sourceType: 'BINARY_DOUBLE', targetType: 'number', notes: '64-bit IEEE double' },
    { sourceType: 'VARCHAR2(n)', targetType: 'string', notes: 'Oracle primary string type; max 32767 bytes' },
    { sourceType: 'NVARCHAR2(n)', targetType: 'string', notes: 'Unicode VARCHAR2' },
    { sourceType: 'CHAR(n) / NCHAR(n)', targetType: 'string' },
    { sourceType: 'CLOB / NCLOB', targetType: 'string', notes: 'Large object; may need streaming in Node.js' },
    { sourceType: 'DATE', targetType: 'Date', notes: 'Oracle DATE includes time (YYYY-MM-DD HH24:MI:SS)' },
    { sourceType: 'TIMESTAMP(n)', targetType: 'Date', notes: 'Fractional seconds precision 0–9' },
    { sourceType: 'TIMESTAMP WITH TIME ZONE', targetType: 'Date', notes: 'Includes timezone; use Date.parse()' },
    { sourceType: 'BLOB', targetType: 'Buffer', notes: 'Binary Large Object; Node.js Buffer' },
    { sourceType: 'RAW(n) / LONG RAW', targetType: 'Buffer' },
    { sourceType: 'SYS_GUID()', targetType: 'string', notes: 'Oracle GUID; 16-byte raw, often hex string' },
    { sourceType: 'XMLTYPE', targetType: 'string', notes: 'XML as string; parse with DOMParser' },
    { sourceType: 'NULL column', targetType: 'field?: Type' },
  ],

  'oracle-to-csharp-poco': [
    { sourceType: 'NUMBER(p,0) / INTEGER', targetType: 'long', notes: 'Oracle NUMBER maps to long for safety' },
    { sourceType: 'NUMBER(p,s) with scale', targetType: 'decimal', notes: 'Exact arithmetic; [Column(TypeName="decimal(p,s)")]' },
    { sourceType: 'BINARY_FLOAT', targetType: 'float' },
    { sourceType: 'BINARY_DOUBLE', targetType: 'double' },
    { sourceType: 'VARCHAR2(n) / NVARCHAR2(n)', targetType: 'string', notes: '[MaxLength(n)]' },
    { sourceType: 'CHAR(n)', targetType: 'string' },
    { sourceType: 'CLOB / NCLOB', targetType: 'string' },
    { sourceType: 'DATE', targetType: 'DateTime', notes: 'Oracle DATE has time component; use DateTime not DateOnly' },
    { sourceType: 'TIMESTAMP(n)', targetType: 'DateTime' },
    { sourceType: 'TIMESTAMP WITH TIME ZONE', targetType: 'DateTimeOffset' },
    { sourceType: 'BLOB', targetType: 'byte[]' },
    { sourceType: 'RAW(n)', targetType: 'byte[]' },
    { sourceType: 'NULL column', targetType: 'Type? Field' },
  ],

  'oracle-to-python-dataclass': [
    { sourceType: 'NUMBER(p,0) / INTEGER', targetType: 'int' },
    { sourceType: 'NUMBER(p,s) with scale', targetType: 'Decimal', notes: 'from decimal import Decimal' },
    { sourceType: 'BINARY_FLOAT / BINARY_DOUBLE', targetType: 'float' },
    { sourceType: 'VARCHAR2(n) / NVARCHAR2(n)', targetType: 'str' },
    { sourceType: 'CLOB / NCLOB', targetType: 'str' },
    { sourceType: 'DATE', targetType: 'datetime', notes: 'Oracle DATE has time; use datetime not date' },
    { sourceType: 'TIMESTAMP(n)', targetType: 'datetime' },
    { sourceType: 'BLOB', targetType: 'bytes' },
    { sourceType: 'RAW(n)', targetType: 'bytes' },
    { sourceType: 'NULL column', targetType: 'Optional[Type] = None' },
  ],

  'oracle-to-java-entity': [
    { sourceType: 'NUMBER(p,0) / INTEGER', targetType: 'Long', notes: 'Oracle NUMBER is arbitrary precision; Long is safe for integers' },
    { sourceType: 'NUMBER(p,s) with scale', targetType: 'BigDecimal', notes: '@Column(precision=p, scale=s)' },
    { sourceType: 'BINARY_FLOAT', targetType: 'Float' },
    { sourceType: 'BINARY_DOUBLE', targetType: 'Double' },
    { sourceType: 'VARCHAR2(n) / NVARCHAR2(n)', targetType: 'String', notes: '@Column(length=n)' },
    { sourceType: 'CLOB', targetType: 'String', notes: '@Lob @Column(columnDefinition="CLOB")' },
    { sourceType: 'DATE', targetType: 'LocalDateTime', notes: 'Oracle DATE includes time; use LocalDateTime' },
    { sourceType: 'TIMESTAMP(n)', targetType: 'LocalDateTime' },
    { sourceType: 'TIMESTAMP WITH TIME ZONE', targetType: 'OffsetDateTime' },
    { sourceType: 'BLOB', targetType: 'byte[]', notes: '@Lob' },
    { sourceType: 'RAW(n)', targetType: 'byte[]' },
    { sourceType: 'NULL column', targetType: 'Type field', notes: '@Column(nullable=true)' },
  ],

  'oracle-to-go-struct': [
    { sourceType: 'NUMBER(p,0) / INTEGER', targetType: 'int64', notes: 'Oracle NUMBER is arbitrary; int64 safe for most integers' },
    { sourceType: 'NUMBER(p,s) with scale', targetType: 'float64', notes: 'Use shopspring/decimal for exact values' },
    { sourceType: 'BINARY_FLOAT', targetType: 'float32' },
    { sourceType: 'BINARY_DOUBLE', targetType: 'float64' },
    { sourceType: 'VARCHAR2(n) / NVARCHAR2(n)', targetType: 'string' },
    { sourceType: 'CLOB', targetType: 'string', notes: 'May need streaming for large values' },
    { sourceType: 'DATE', targetType: 'time.Time', notes: 'Oracle DATE has time; godror returns time.Time' },
    { sourceType: 'TIMESTAMP(n)', targetType: 'time.Time' },
    { sourceType: 'BLOB', targetType: '[]byte' },
    { sourceType: 'RAW(n)', targetType: '[]byte' },
    { sourceType: 'NULL column', targetType: '*Type' },
  ],

  'oracle-to-mock-json': [
    { sourceType: 'NUMBER(p,0)', targetType: 'Number (integer)' },
    { sourceType: 'NUMBER(p,s)', targetType: 'Number (float)', notes: 'Rounded to s decimal places' },
    { sourceType: 'VARCHAR2(n) — name', targetType: 'Faker full name' },
    { sourceType: 'VARCHAR2(n) — email', targetType: 'Faker email' },
    { sourceType: 'CLOB', targetType: 'Faker lorem paragraph' },
    { sourceType: 'DATE / TIMESTAMP', targetType: 'ISO 8601 string' },
    { sourceType: 'BLOB', targetType: 'Base64 string' },
    { sourceType: 'NULL column', targetType: 'Occasionally null' },
  ],

  'oracle-to-sql-inserts': [
    { sourceType: 'NUMBER(p,0)', targetType: 'INTEGER literal' },
    { sourceType: 'NUMBER(p,s)', targetType: 'NUMERIC literal', notes: 'e.g. 1234.56' },
    { sourceType: 'VARCHAR2(n) / NVARCHAR2', targetType: "String literal", notes: "Single-quoted: 'value'" },
    { sourceType: 'DATE', targetType: "TO_DATE('YYYY-MM-DD HH24:MI:SS', ...) literal" },
    { sourceType: 'TIMESTAMP', targetType: "TIMESTAMP 'YYYY-MM-DD HH24:MI:SS.FF' literal" },
    { sourceType: 'BLOB', targetType: 'HEXTORAW() or EMPTY_BLOB()' },
    { sourceType: 'NULL', targetType: 'NULL' },
  ],

  // ── MariaDB → * ────────────────────────────────────────────────────────────
  // MariaDB is MySQL-compatible with a few extras

  'mariadb-to-typescript': [
    { sourceType: 'INT AUTO_INCREMENT', targetType: 'number', notes: 'Auto-increment PK; identical to MySQL' },
    { sourceType: 'BIGINT AUTO_INCREMENT', targetType: 'number' },
    { sourceType: 'INT / INTEGER', targetType: 'number' },
    { sourceType: 'BIGINT', targetType: 'number' },
    { sourceType: 'TINYINT(1)', targetType: 'boolean', notes: 'MariaDB boolean; same as MySQL' },
    { sourceType: 'FLOAT / DOUBLE', targetType: 'number' },
    { sourceType: 'DECIMAL(p,s)', targetType: 'number', notes: 'Use string for exact financials' },
    { sourceType: 'VARCHAR(n)', targetType: 'string' },
    { sourceType: 'TEXT / MEDIUMTEXT / LONGTEXT', targetType: 'string' },
    { sourceType: 'DATETIME', targetType: 'Date', notes: 'No timezone stored' },
    { sourceType: 'TIMESTAMP', targetType: 'Date', notes: 'UTC-stored; auto-converts on retrieval' },
    { sourceType: 'DATE', targetType: 'string', notes: 'Returns YYYY-MM-DD string' },
    { sourceType: 'JSON (MariaDB 10.2+)', targetType: 'Record<string, unknown>', notes: 'MariaDB stores JSON as LONGTEXT internally' },
    { sourceType: 'UUID (MariaDB 10.7+)', targetType: 'string', notes: 'Native UUID type; MariaDB 10.7+' },
    { sourceType: 'INET4 / INET6 (MariaDB 10.5+)', targetType: 'string', notes: 'IP address as string' },
    { sourceType: 'BLOB', targetType: 'Buffer', notes: 'Binary data' },
    { sourceType: 'ENUM', targetType: "'val1' | 'val2'", notes: 'TypeScript string literal union' },
    { sourceType: 'NULL column', targetType: 'field?: Type' },
  ],

  'mariadb-to-csharp-poco': [
    { sourceType: 'INT AUTO_INCREMENT', targetType: 'int', notes: '[Key] [DatabaseGenerated(DatabaseGeneratedOption.Identity)]' },
    { sourceType: 'BIGINT AUTO_INCREMENT', targetType: 'long' },
    { sourceType: 'INT', targetType: 'int' },
    { sourceType: 'BIGINT', targetType: 'long' },
    { sourceType: 'TINYINT(1)', targetType: 'bool' },
    { sourceType: 'FLOAT', targetType: 'float' },
    { sourceType: 'DOUBLE', targetType: 'double' },
    { sourceType: 'DECIMAL(p,s)', targetType: 'decimal' },
    { sourceType: 'VARCHAR(n) / TEXT', targetType: 'string' },
    { sourceType: 'DATETIME', targetType: 'DateTime' },
    { sourceType: 'TIMESTAMP', targetType: 'DateTime' },
    { sourceType: 'DATE', targetType: 'DateOnly', notes: '.NET 6+' },
    { sourceType: 'JSON (10.2+)', targetType: 'string', notes: 'Store as string or use custom converter' },
    { sourceType: 'UUID (10.7+)', targetType: 'Guid' },
    { sourceType: 'BLOB', targetType: 'byte[]' },
    { sourceType: 'NULL column', targetType: 'Type? Field' },
  ],

  'mariadb-to-python-dataclass': [
    { sourceType: 'INT AUTO_INCREMENT', targetType: 'int', notes: 'field(default=None) for auto PK' },
    { sourceType: 'INT', targetType: 'int' },
    { sourceType: 'BIGINT', targetType: 'int' },
    { sourceType: 'TINYINT(1)', targetType: 'bool' },
    { sourceType: 'FLOAT / DOUBLE', targetType: 'float' },
    { sourceType: 'DECIMAL(p,s)', targetType: 'Decimal', notes: 'from decimal import Decimal' },
    { sourceType: 'VARCHAR(n) / TEXT', targetType: 'str' },
    { sourceType: 'DATETIME', targetType: 'datetime', notes: 'from datetime import datetime' },
    { sourceType: 'TIMESTAMP', targetType: 'datetime', notes: 'UTC-aware datetime recommended' },
    { sourceType: 'DATE', targetType: 'date', notes: 'from datetime import date' },
    { sourceType: 'JSON (10.2+)', targetType: 'dict[str, Any]', notes: 'from typing import Any' },
    { sourceType: 'UUID (10.7+)', targetType: 'UUID', notes: 'from uuid import UUID' },
    { sourceType: 'INET4 / INET6', targetType: 'str', notes: 'Validate with ipaddress module' },
    { sourceType: 'BLOB', targetType: 'bytes' },
    { sourceType: 'ENUM', targetType: 'str', notes: 'Or Python Enum class' },
    { sourceType: 'NULL column', targetType: 'Optional[Type] = None' },
  ],

  'mariadb-to-java-entity': [
    { sourceType: 'INT AUTO_INCREMENT', targetType: 'Integer', notes: '@Id @GeneratedValue(strategy=IDENTITY)' },
    { sourceType: 'BIGINT AUTO_INCREMENT', targetType: 'Long' },
    { sourceType: 'INT', targetType: 'Integer' },
    { sourceType: 'BIGINT', targetType: 'Long' },
    { sourceType: 'TINYINT(1)', targetType: 'Boolean' },
    { sourceType: 'FLOAT', targetType: 'Float' },
    { sourceType: 'DOUBLE', targetType: 'Double' },
    { sourceType: 'DECIMAL(p,s)', targetType: 'BigDecimal', notes: '@Column(precision=p, scale=s)' },
    { sourceType: 'VARCHAR(n)', targetType: 'String', notes: '@Column(length=n)' },
    { sourceType: 'TEXT', targetType: 'String', notes: '@Column(columnDefinition="TEXT")' },
    { sourceType: 'DATETIME / TIMESTAMP', targetType: 'LocalDateTime' },
    { sourceType: 'DATE', targetType: 'LocalDate' },
    { sourceType: 'JSON (10.2+)', targetType: 'String', notes: '@Column(columnDefinition="JSON")' },
    { sourceType: 'UUID (10.7+)', targetType: 'UUID' },
    { sourceType: 'BLOB', targetType: 'byte[]', notes: '@Lob' },
    { sourceType: 'NULL column', targetType: 'Type field', notes: '@Column(nullable=true)' },
  ],

  'mariadb-to-go-struct': [
    { sourceType: 'INT AUTO_INCREMENT', targetType: 'int', notes: '`gorm:"primaryKey;autoIncrement"`' },
    { sourceType: 'BIGINT AUTO_INCREMENT', targetType: 'int64' },
    { sourceType: 'INT', targetType: 'int' },
    { sourceType: 'BIGINT', targetType: 'int64' },
    { sourceType: 'TINYINT(1)', targetType: 'bool' },
    { sourceType: 'FLOAT', targetType: 'float32' },
    { sourceType: 'DOUBLE', targetType: 'float64' },
    { sourceType: 'DECIMAL(p,s)', targetType: 'float64', notes: 'Or shopspring/decimal' },
    { sourceType: 'VARCHAR(n) / TEXT', targetType: 'string' },
    { sourceType: 'DATETIME / TIMESTAMP', targetType: 'time.Time' },
    { sourceType: 'DATE', targetType: 'time.Time', notes: 'Time portion will be zero' },
    { sourceType: 'JSON (10.2+)', targetType: 'json.RawMessage' },
    { sourceType: 'UUID (10.7+)', targetType: 'string', notes: 'Or uuid.UUID' },
    { sourceType: 'BLOB', targetType: '[]byte' },
    { sourceType: 'NULL column', targetType: '*Type' },
  ],

  'mariadb-to-mock-json': [
    { sourceType: 'INT AUTO_INCREMENT', targetType: 'Number (integer)', notes: 'Sequential' },
    { sourceType: 'VARCHAR(n) — name', targetType: 'Faker full name' },
    { sourceType: 'VARCHAR(n) — email', targetType: 'Faker email' },
    { sourceType: 'TINYINT(1)', targetType: 'true / false' },
    { sourceType: 'DATETIME / TIMESTAMP', targetType: 'ISO 8601 string' },
    { sourceType: 'DECIMAL', targetType: 'Number (float, 2dp)' },
    { sourceType: 'JSON (10.2+)', targetType: 'Nested JSON object' },
    { sourceType: 'UUID (10.7+)', targetType: 'UUID v4 string' },
    { sourceType: 'INET4 / INET6', targetType: 'IP address string', notes: 'e.g. "192.168.1.1"' },
    { sourceType: 'NULL column', targetType: 'Occasionally null' },
  ],

  'mariadb-to-sql-inserts': [
    { sourceType: 'INT AUTO_INCREMENT', targetType: 'INTEGER literal' },
    { sourceType: 'VARCHAR / TEXT', targetType: "String literal", notes: "Single-quoted: 'value'" },
    { sourceType: 'TINYINT(1)', targetType: '0 / 1' },
    { sourceType: 'DATETIME / TIMESTAMP', targetType: "'YYYY-MM-DD HH:MM:SS' literal" },
    { sourceType: 'JSON (10.2+)', targetType: "JSON string literal" },
    { sourceType: 'UUID (10.7+)', targetType: "'xxxxxxxx-xxxx-...' literal" },
    { sourceType: 'NULL', targetType: 'NULL' },
  ],
};

// ─── Convert routes: SQL dialect → SQL dialect ───────────────────────────────

export const convertMappings: Record<string, TypeRow[]> = {

  'postgres-to-mysql': [
    { sourceType: 'SERIAL', targetType: 'INT AUTO_INCREMENT', notes: 'Add AUTO_INCREMENT to INT column' },
    { sourceType: 'BIGSERIAL', targetType: 'BIGINT AUTO_INCREMENT' },
    { sourceType: 'SMALLSERIAL', targetType: 'SMALLINT AUTO_INCREMENT' },
    { sourceType: 'INTEGER / INT4', targetType: 'INT' },
    { sourceType: 'BIGINT / INT8', targetType: 'BIGINT' },
    { sourceType: 'SMALLINT / INT2', targetType: 'SMALLINT' },
    { sourceType: 'BOOLEAN / BOOL', targetType: 'TINYINT(1)', notes: 'MySQL has no native BOOL; uses 0/1' },
    { sourceType: 'TEXT', targetType: 'LONGTEXT', notes: 'MySQL TEXT is limited to 65,535 bytes' },
    { sourceType: 'VARCHAR(n)', targetType: 'VARCHAR(n)', notes: 'Same syntax; max 65,535 bytes in MySQL' },
    { sourceType: 'BYTEA', targetType: 'BLOB', notes: 'Binary data' },
    { sourceType: 'TIMESTAMP', targetType: 'DATETIME', notes: 'MySQL TIMESTAMP is UTC-only and has year-2038 limit; prefer DATETIME' },
    { sourceType: 'TIMESTAMP WITH TIME ZONE', targetType: 'DATETIME', notes: 'MySQL has no timezone-aware datetime; store UTC' },
    { sourceType: 'JSONB', targetType: 'JSON', notes: 'MySQL 5.7+; no operator support like Postgres JSONB' },
    { sourceType: 'UUID', targetType: 'CHAR(36)', notes: 'MySQL has no UUID type; use CHAR(36) or BINARY(16)' },
    { sourceType: 'DOUBLE PRECISION', targetType: 'DOUBLE' },
    { sourceType: 'REAL', targetType: 'FLOAT' },
    { sourceType: 'NUMERIC(p,s)', targetType: 'DECIMAL(p,s)' },
    { sourceType: 'SERIAL PRIMARY KEY', targetType: 'INT AUTO_INCREMENT PRIMARY KEY' },
    { sourceType: 'CHARACTER VARYING(n)', targetType: 'VARCHAR(n)' },
  ],

  'postgres-to-sqlite': [
    { sourceType: 'SERIAL / BIGSERIAL', targetType: 'INTEGER', notes: 'INTEGER PRIMARY KEY auto-increments in SQLite (rowid alias)' },
    { sourceType: 'INTEGER / INT / BIGINT', targetType: 'INTEGER', notes: 'SQLite stores all integers as up to 8-byte signed int' },
    { sourceType: 'BOOLEAN / BOOL', targetType: 'INTEGER', notes: 'SQLite uses 0/1 for booleans' },
    { sourceType: 'REAL / FLOAT / DOUBLE PRECISION', targetType: 'REAL', notes: '8-byte IEEE float' },
    { sourceType: 'NUMERIC(p,s) / DECIMAL(p,s)', targetType: 'NUMERIC', notes: 'SQLite NUMERIC affinity; may store as INTEGER or REAL' },
    { sourceType: 'VARCHAR(n) / TEXT / CHAR(n)', targetType: 'TEXT', notes: 'SQLite has no length limit on TEXT' },
    { sourceType: 'BYTEA', targetType: 'BLOB', notes: 'Binary Large Object' },
    { sourceType: 'TIMESTAMP / TIMESTAMPTZ', targetType: 'TEXT', notes: "SQLite stores as ISO 8601 string: '2024-01-15 09:30:00'" },
    { sourceType: 'DATE', targetType: 'TEXT', notes: "Store as 'YYYY-MM-DD'" },
    { sourceType: 'TIME', targetType: 'TEXT', notes: "Store as 'HH:MM:SS'" },
    { sourceType: 'UUID', targetType: 'TEXT', notes: 'SQLite has no UUID type; store as 36-char string' },
    { sourceType: 'JSONB / JSON', targetType: 'TEXT', notes: 'SQLite 3.38+ has json_extract() for TEXT columns' },
    { sourceType: 'SERIAL PRIMARY KEY', targetType: 'INTEGER PRIMARY KEY', notes: 'SQLite rowid alias — auto-increments' },
  ],

  'postgres-to-sql-server': [
    { sourceType: 'SERIAL', targetType: 'INT IDENTITY(1,1)', notes: 'SQL Server identity column syntax' },
    { sourceType: 'BIGSERIAL', targetType: 'BIGINT IDENTITY(1,1)' },
    { sourceType: 'BOOLEAN / BOOL', targetType: 'BIT', notes: 'SQL Server boolean type; 0=false, 1=true' },
    { sourceType: 'TEXT', targetType: 'NVARCHAR(MAX)', notes: 'Use NVARCHAR(MAX) for unlimited Unicode text' },
    { sourceType: 'VARCHAR(n)', targetType: 'NVARCHAR(n)', notes: 'Use NVARCHAR for Unicode support' },
    { sourceType: 'BYTEA', targetType: 'VARBINARY(MAX)' },
    { sourceType: 'TIMESTAMP', targetType: 'DATETIME2', notes: 'DATETIME2 has higher precision than DATETIME' },
    { sourceType: 'TIMESTAMP WITH TIME ZONE', targetType: 'DATETIMEOFFSET', notes: 'Preserves timezone offset' },
    { sourceType: 'JSONB / JSON', targetType: 'NVARCHAR(MAX)', notes: 'SQL Server 2016+ has JSON functions; no native JSON column type' },
    { sourceType: 'UUID', targetType: 'UNIQUEIDENTIFIER', notes: 'SQL Server native GUID type; use NEWID()' },
    { sourceType: 'DOUBLE PRECISION', targetType: 'FLOAT', notes: 'SQL Server FLOAT is 64-bit by default' },
    { sourceType: 'REAL', targetType: 'REAL', notes: 'Same name; 32-bit float' },
    { sourceType: 'SERIAL PRIMARY KEY', targetType: 'INT IDENTITY(1,1) PRIMARY KEY' },
    { sourceType: 'NUMERIC(p,s) / DECIMAL(p,s)', targetType: 'NUMERIC(p,s) / DECIMAL(p,s)', notes: 'Same syntax' },
  ],

  'mysql-to-postgres': [
    { sourceType: 'INT AUTO_INCREMENT', targetType: 'SERIAL', notes: 'Or INTEGER DEFAULT nextval(seq)' },
    { sourceType: 'BIGINT AUTO_INCREMENT', targetType: 'BIGSERIAL' },
    { sourceType: 'TINYINT(1)', targetType: 'BOOLEAN', notes: 'PostgreSQL has native BOOL type' },
    { sourceType: 'TINYINT', targetType: 'SMALLINT', notes: 'PostgreSQL has no TINYINT; use SMALLINT' },
    { sourceType: 'DATETIME', targetType: 'TIMESTAMP', notes: 'PostgreSQL TIMESTAMP (no timezone)' },
    { sourceType: 'LONGTEXT / MEDIUMTEXT', targetType: 'TEXT', notes: 'PostgreSQL TEXT has no length limit' },
    { sourceType: 'JSON', targetType: 'JSONB', notes: 'JSONB is preferred in PostgreSQL; indexable' },
    { sourceType: 'CHAR(36) (UUID)', targetType: 'UUID', notes: 'Use native UUID type in PostgreSQL' },
    { sourceType: 'FLOAT', targetType: 'REAL', notes: '32-bit float' },
    { sourceType: 'DOUBLE / DOUBLE PRECISION', targetType: 'DOUBLE PRECISION' },
    { sourceType: 'DECIMAL(p,s)', targetType: 'NUMERIC(p,s)' },
    { sourceType: 'ENUM(\'a\',\'b\')', targetType: "CREATE TYPE enum_name AS ENUM ('a','b')", notes: 'Define a PostgreSQL ENUM type first' },
    { sourceType: 'BLOB', targetType: 'BYTEA' },
    { sourceType: 'INT AUTO_INCREMENT PRIMARY KEY', targetType: 'SERIAL PRIMARY KEY' },
  ],

  'mysql-to-sqlite': [
    { sourceType: 'INT AUTO_INCREMENT', targetType: 'INTEGER', notes: 'INTEGER PRIMARY KEY auto-increments in SQLite' },
    { sourceType: 'BIGINT', targetType: 'INTEGER', notes: 'SQLite stores all ints as 8-byte signed int' },
    { sourceType: 'TINYINT(1)', targetType: 'INTEGER', notes: 'Store 0 or 1 for boolean' },
    { sourceType: 'FLOAT / DOUBLE', targetType: 'REAL' },
    { sourceType: 'DECIMAL(p,s)', targetType: 'NUMERIC', notes: 'SQLite NUMERIC may store as int or real' },
    { sourceType: 'VARCHAR(n) / TEXT / LONGTEXT', targetType: 'TEXT', notes: 'SQLite TEXT has no length limit' },
    { sourceType: 'DATETIME / TIMESTAMP', targetType: 'TEXT', notes: "Store as ISO 8601: '2024-01-15 09:30:00'" },
    { sourceType: 'DATE', targetType: 'TEXT', notes: "'YYYY-MM-DD'" },
    { sourceType: 'BLOB', targetType: 'BLOB' },
    { sourceType: 'JSON', targetType: 'TEXT', notes: 'SQLite 3.38+ has json_extract() for TEXT' },
    { sourceType: 'ENUM(\'a\',\'b\')', targetType: 'TEXT', notes: 'Add CHECK constraint: CHECK(col IN (\'a\',\'b\'))' },
  ],

  'mysql-to-sql-server': [
    { sourceType: 'INT AUTO_INCREMENT', targetType: 'INT IDENTITY(1,1)' },
    { sourceType: 'BIGINT AUTO_INCREMENT', targetType: 'BIGINT IDENTITY(1,1)' },
    { sourceType: 'TINYINT(1)', targetType: 'BIT', notes: 'SQL Server BIT for boolean' },
    { sourceType: 'TINYINT', targetType: 'TINYINT', notes: 'Same name; SQL Server TINYINT is 0–255 (unsigned)' },
    { sourceType: 'DATETIME', targetType: 'DATETIME2', notes: 'DATETIME2 has higher precision' },
    { sourceType: 'TIMESTAMP', targetType: 'DATETIME2', notes: 'Note: SQL Server TIMESTAMP is a different, binary type' },
    { sourceType: 'TEXT / LONGTEXT', targetType: 'NVARCHAR(MAX)', notes: 'Unicode max-length string' },
    { sourceType: 'VARCHAR(n)', targetType: 'NVARCHAR(n)', notes: 'Use NVARCHAR for Unicode' },
    { sourceType: 'JSON', targetType: 'NVARCHAR(MAX)', notes: 'SQL Server 2016+ has JSON functions on NVARCHAR' },
    { sourceType: 'FLOAT', targetType: 'REAL' },
    { sourceType: 'DOUBLE', targetType: 'FLOAT', notes: 'SQL Server FLOAT is 64-bit' },
    { sourceType: 'DECIMAL(p,s)', targetType: 'DECIMAL(p,s)', notes: 'Same syntax' },
    { sourceType: 'BLOB', targetType: 'VARBINARY(MAX)' },
    { sourceType: 'ENUM(\'a\',\'b\')', targetType: 'NVARCHAR(n)', notes: 'Add CHECK constraint: CHECK(col IN (\'a\',\'b\'))' },
  ],

  'sqlite-to-postgres': [
    { sourceType: 'INTEGER PRIMARY KEY', targetType: 'SERIAL PRIMARY KEY', notes: 'Or BIGSERIAL for large tables' },
    { sourceType: 'INTEGER', targetType: 'INTEGER', notes: 'Postgres has full integer type range; use appropriate' },
    { sourceType: 'REAL', targetType: 'DOUBLE PRECISION', notes: 'SQLite REAL is 64-bit; maps to DOUBLE PRECISION' },
    { sourceType: 'NUMERIC', targetType: 'NUMERIC', notes: 'Add precision/scale: NUMERIC(p,s)' },
    { sourceType: 'TEXT', targetType: 'TEXT', notes: 'Identical; unlimited length in both' },
    { sourceType: 'BLOB', targetType: 'BYTEA', notes: 'PostgreSQL binary type' },
    { sourceType: 'TEXT (boolean 0/1)', targetType: 'BOOLEAN', notes: 'Cast data: CAST(col AS BOOLEAN)' },
    { sourceType: 'TEXT (datetime)', targetType: 'TIMESTAMP', notes: 'Cast: CAST(col AS TIMESTAMP)' },
    { sourceType: 'TEXT (date)', targetType: 'DATE', notes: 'Cast: CAST(col AS DATE)' },
    { sourceType: 'TEXT (UUID)', targetType: 'UUID', notes: 'Cast: CAST(col AS UUID)' },
    { sourceType: 'TEXT (JSON)', targetType: 'JSONB', notes: 'Cast: CAST(col AS JSONB) — add GIN index' },
  ],

  'sqlite-to-mysql': [
    { sourceType: 'INTEGER PRIMARY KEY', targetType: 'INT AUTO_INCREMENT PRIMARY KEY' },
    { sourceType: 'INTEGER', targetType: 'INT', notes: 'Or BIGINT for large values' },
    { sourceType: 'REAL', targetType: 'DOUBLE', notes: '64-bit float' },
    { sourceType: 'NUMERIC', targetType: 'DECIMAL(p,s)', notes: 'Add explicit precision/scale' },
    { sourceType: 'TEXT', targetType: 'LONGTEXT', notes: 'Or VARCHAR(n) with explicit length' },
    { sourceType: 'BLOB', targetType: 'BLOB' },
    { sourceType: 'TEXT (boolean 0/1)', targetType: 'TINYINT(1)', notes: 'MySQL boolean convention' },
    { sourceType: 'TEXT (datetime)', targetType: 'DATETIME', notes: 'MySQL DATETIME for local datetime' },
    { sourceType: 'TEXT (date)', targetType: 'DATE' },
    { sourceType: 'TEXT (JSON)', targetType: 'JSON', notes: 'MySQL 5.7+' },
  ],

  'sqlite-to-sql-server': [
    { sourceType: 'INTEGER PRIMARY KEY', targetType: 'INT IDENTITY(1,1) PRIMARY KEY' },
    { sourceType: 'INTEGER', targetType: 'INT', notes: 'Or BIGINT for large values' },
    { sourceType: 'REAL', targetType: 'FLOAT', notes: 'SQL Server FLOAT is 64-bit' },
    { sourceType: 'NUMERIC', targetType: 'NUMERIC(p,s)', notes: 'Add explicit precision/scale' },
    { sourceType: 'TEXT', targetType: 'NVARCHAR(MAX)', notes: 'Unicode unlimited text' },
    { sourceType: 'BLOB', targetType: 'VARBINARY(MAX)' },
    { sourceType: 'TEXT (boolean 0/1)', targetType: 'BIT', notes: 'SQL Server boolean' },
    { sourceType: 'TEXT (datetime)', targetType: 'DATETIME2', notes: 'High-precision datetime' },
    { sourceType: 'TEXT (JSON)', targetType: 'NVARCHAR(MAX)', notes: 'SQL Server 2016+ JSON functions' },
  ],

  'sql-server-to-postgres': [
    { sourceType: 'INT IDENTITY(1,1)', targetType: 'SERIAL', notes: 'Or INTEGER DEFAULT nextval(seq)' },
    { sourceType: 'BIGINT IDENTITY(1,1)', targetType: 'BIGSERIAL' },
    { sourceType: 'BIT', targetType: 'BOOLEAN', notes: 'PostgreSQL native BOOL' },
    { sourceType: 'NVARCHAR(n) / VARCHAR(n)', targetType: 'VARCHAR(n)', notes: 'PostgreSQL is Unicode by default' },
    { sourceType: 'NVARCHAR(MAX)', targetType: 'TEXT', notes: 'Unlimited text' },
    { sourceType: 'NTEXT / TEXT', targetType: 'TEXT' },
    { sourceType: 'DATETIME / DATETIME2', targetType: 'TIMESTAMP', notes: 'Or TIMESTAMPTZ for timezone-awareness' },
    { sourceType: 'DATETIMEOFFSET', targetType: 'TIMESTAMP WITH TIME ZONE' },
    { sourceType: 'SMALLDATETIME', targetType: 'TIMESTAMP', notes: 'Lower precision; still maps to TIMESTAMP' },
    { sourceType: 'UNIQUEIDENTIFIER', targetType: 'UUID', notes: 'PostgreSQL native UUID type' },
    { sourceType: 'VARBINARY(n) / VARBINARY(MAX)', targetType: 'BYTEA' },
    { sourceType: 'IMAGE', targetType: 'BYTEA', notes: 'Deprecated SQL Server type' },
    { sourceType: 'MONEY / SMALLMONEY', targetType: 'NUMERIC(p,s)', notes: 'Use NUMERIC for exact monetary values' },
    { sourceType: 'NVARCHAR(MAX) (JSON)', targetType: 'JSONB', notes: 'Add GIN index after migration' },
    { sourceType: 'TINYINT', targetType: 'SMALLINT', notes: 'PostgreSQL has no TINYINT; min is SMALLINT' },
    { sourceType: 'FLOAT', targetType: 'DOUBLE PRECISION' },
    { sourceType: 'REAL', targetType: 'REAL' },
  ],

  'sql-server-to-mysql': [
    { sourceType: 'INT IDENTITY(1,1)', targetType: 'INT AUTO_INCREMENT' },
    { sourceType: 'BIGINT IDENTITY(1,1)', targetType: 'BIGINT AUTO_INCREMENT' },
    { sourceType: 'BIT', targetType: 'TINYINT(1)', notes: 'MySQL boolean convention' },
    { sourceType: 'NVARCHAR(n)', targetType: 'VARCHAR(n)', notes: 'Use utf8mb4 character set for Unicode' },
    { sourceType: 'NVARCHAR(MAX)', targetType: 'LONGTEXT', notes: 'Unlimited text in MySQL' },
    { sourceType: 'DATETIME2', targetType: 'DATETIME', notes: 'MySQL DATETIME has microsecond precision in 5.6+' },
    { sourceType: 'DATETIMEOFFSET', targetType: 'DATETIME', notes: 'MySQL has no timezone-aware datetime; store UTC' },
    { sourceType: 'UNIQUEIDENTIFIER', targetType: 'CHAR(36)', notes: 'MySQL has no GUID; use CHAR(36) or BINARY(16)' },
    { sourceType: 'VARBINARY(MAX)', targetType: 'LONGBLOB' },
    { sourceType: 'MONEY / SMALLMONEY', targetType: 'DECIMAL(p,s)', notes: 'Use explicit precision/scale' },
    { sourceType: 'TINYINT', targetType: 'TINYINT UNSIGNED', notes: 'SQL Server TINYINT is 0–255; MySQL matches' },
    { sourceType: 'FLOAT', targetType: 'DOUBLE' },
  ],

  'sql-server-to-sqlite': [
    { sourceType: 'INT IDENTITY(1,1)', targetType: 'INTEGER PRIMARY KEY', notes: 'SQLite rowid auto-increments' },
    { sourceType: 'BIGINT', targetType: 'INTEGER' },
    { sourceType: 'BIT', targetType: 'INTEGER', notes: 'Store 0 or 1' },
    { sourceType: 'NVARCHAR / VARCHAR', targetType: 'TEXT', notes: 'SQLite TEXT has no length limit' },
    { sourceType: 'FLOAT / REAL', targetType: 'REAL' },
    { sourceType: 'DECIMAL / NUMERIC', targetType: 'NUMERIC' },
    { sourceType: 'DATETIME2 / DATETIME', targetType: 'TEXT', notes: "Store ISO 8601: '2024-01-15 09:30:00'" },
    { sourceType: 'UNIQUEIDENTIFIER', targetType: 'TEXT', notes: '36-char UUID string' },
    { sourceType: 'VARBINARY', targetType: 'BLOB' },
    { sourceType: 'MONEY', targetType: 'NUMERIC', notes: 'SQLite stores exact if NUMERIC affinity' },
  ],

  'oracle-to-postgres': [
    { sourceType: 'NUMBER(p,0) / INTEGER', targetType: 'INTEGER', notes: 'Or BIGINT; use SERIAL for auto-increment' },
    { sourceType: 'NUMBER(p,s) with scale > 0', targetType: 'NUMERIC(p,s)', notes: 'Exact arbitrary precision' },
    { sourceType: 'BINARY_FLOAT', targetType: 'REAL', notes: '32-bit IEEE float' },
    { sourceType: 'BINARY_DOUBLE', targetType: 'DOUBLE PRECISION', notes: '64-bit IEEE float' },
    { sourceType: 'VARCHAR2(n)', targetType: 'VARCHAR(n)', notes: 'PostgreSQL is Unicode by default' },
    { sourceType: 'NVARCHAR2(n)', targetType: 'VARCHAR(n)', notes: 'No prefix needed in PostgreSQL' },
    { sourceType: 'CHAR(n) / NCHAR(n)', targetType: 'CHAR(n)' },
    { sourceType: 'CLOB / NCLOB', targetType: 'TEXT', notes: 'Unlimited text in PostgreSQL' },
    { sourceType: 'DATE', targetType: 'TIMESTAMP', notes: 'Oracle DATE has time component! Do NOT use DATE in Postgres if time matters' },
    { sourceType: 'TIMESTAMP(n)', targetType: 'TIMESTAMP(n)', notes: 'Same semantics' },
    { sourceType: 'TIMESTAMP WITH TIME ZONE', targetType: 'TIMESTAMP WITH TIME ZONE' },
    { sourceType: 'BLOB', targetType: 'BYTEA' },
    { sourceType: 'RAW(n)', targetType: 'BYTEA' },
    { sourceType: 'XMLTYPE', targetType: 'XML', notes: 'PostgreSQL has native XML type' },
    { sourceType: 'SYS_GUID() / RAW(16)', targetType: 'UUID', notes: 'PostgreSQL UUID type with gen_random_uuid()' },
    { sourceType: 'SEQUENCE + TRIGGER', targetType: 'SERIAL / BIGSERIAL', notes: 'PostgreSQL auto-increment is simpler' },
    { sourceType: 'DUAL (SELECT ... FROM DUAL)', targetType: 'Remove FROM clause', notes: 'PostgreSQL SELECT 1 (no DUAL)' },
    { sourceType: 'NVL(x, y)', targetType: 'COALESCE(x, y)', notes: 'Standard SQL null coalescing' },
  ],

  'oracle-to-mysql': [
    { sourceType: 'NUMBER(p,0) / INTEGER', targetType: 'INT', notes: 'Or BIGINT for large numbers' },
    { sourceType: 'NUMBER(p,s) with scale', targetType: 'DECIMAL(p,s)' },
    { sourceType: 'BINARY_FLOAT', targetType: 'FLOAT' },
    { sourceType: 'BINARY_DOUBLE', targetType: 'DOUBLE' },
    { sourceType: 'VARCHAR2(n)', targetType: 'VARCHAR(n)', notes: 'Use utf8mb4 charset for Unicode' },
    { sourceType: 'NVARCHAR2(n)', targetType: 'VARCHAR(n)', notes: 'utf8mb4 handles Unicode in MySQL' },
    { sourceType: 'CLOB / NCLOB', targetType: 'LONGTEXT' },
    { sourceType: 'DATE', targetType: 'DATETIME', notes: 'Oracle DATE has time; use DATETIME in MySQL' },
    { sourceType: 'TIMESTAMP(n)', targetType: 'DATETIME(n)', notes: 'MySQL 5.6+ supports fractional seconds' },
    { sourceType: 'BLOB', targetType: 'LONGBLOB' },
    { sourceType: 'RAW(n)', targetType: 'VARBINARY(n)' },
    { sourceType: 'SEQUENCE + TRIGGER', targetType: 'INT AUTO_INCREMENT', notes: 'MySQL native auto-increment' },
    { sourceType: 'SYS_GUID()', targetType: 'CHAR(36)', notes: 'Store UUID as CHAR(36)' },
    { sourceType: 'DUAL', targetType: 'DUAL', notes: 'MySQL also has DUAL table' },
    { sourceType: 'NVL(x, y)', targetType: 'IFNULL(x, y)', notes: 'MySQL null coalescing function' },
  ],

  'oracle-to-sqlite': [
    { sourceType: 'NUMBER(p,0) with auto PK', targetType: 'INTEGER PRIMARY KEY', notes: 'SQLite rowid auto-increments' },
    { sourceType: 'NUMBER(p,0) / INTEGER', targetType: 'INTEGER' },
    { sourceType: 'NUMBER(p,s) / BINARY_DOUBLE', targetType: 'REAL' },
    { sourceType: 'BINARY_FLOAT', targetType: 'REAL' },
    { sourceType: 'VARCHAR2(n) / NVARCHAR2(n)', targetType: 'TEXT' },
    { sourceType: 'CLOB / NCLOB', targetType: 'TEXT' },
    { sourceType: 'DATE', targetType: 'TEXT', notes: "ISO 8601 '2024-01-15 09:30:00'" },
    { sourceType: 'TIMESTAMP', targetType: 'TEXT', notes: "ISO 8601 string" },
    { sourceType: 'BLOB / RAW', targetType: 'BLOB' },
    { sourceType: 'DECIMAL(p,s)', targetType: 'NUMERIC' },
  ],

  'oracle-to-sql-server': [
    { sourceType: 'NUMBER(p,0) — PK with SEQUENCE', targetType: 'INT IDENTITY(1,1)', notes: 'SQL Server native auto-increment' },
    { sourceType: 'NUMBER(p,0) / INTEGER', targetType: 'INT', notes: 'Or BIGINT for large numbers' },
    { sourceType: 'NUMBER(p,s) with scale', targetType: 'DECIMAL(p,s)' },
    { sourceType: 'BINARY_FLOAT', targetType: 'REAL' },
    { sourceType: 'BINARY_DOUBLE', targetType: 'FLOAT', notes: 'SQL Server FLOAT is 64-bit' },
    { sourceType: 'VARCHAR2(n)', targetType: 'NVARCHAR(n)', notes: 'Use NVARCHAR for Unicode' },
    { sourceType: 'NVARCHAR2(n)', targetType: 'NVARCHAR(n)' },
    { sourceType: 'CLOB / NCLOB', targetType: 'NVARCHAR(MAX)' },
    { sourceType: 'DATE', targetType: 'DATETIME2', notes: 'Oracle DATE has time; DATETIME2 is high-precision' },
    { sourceType: 'TIMESTAMP(n)', targetType: 'DATETIME2(n)' },
    { sourceType: 'TIMESTAMP WITH TIME ZONE', targetType: 'DATETIMEOFFSET' },
    { sourceType: 'BLOB', targetType: 'VARBINARY(MAX)' },
    { sourceType: 'RAW(n)', targetType: 'VARBINARY(n)' },
    { sourceType: 'SYS_GUID()', targetType: 'UNIQUEIDENTIFIER', notes: 'Use NEWID() in SQL Server' },
    { sourceType: 'XMLTYPE', targetType: 'XML', notes: 'SQL Server has native XML type' },
    { sourceType: 'NVL(x, y)', targetType: 'ISNULL(x, y)', notes: 'SQL Server null coalescing' },
  ],

  'mariadb-to-postgres': [
    { sourceType: 'INT AUTO_INCREMENT', targetType: 'SERIAL', notes: 'Or INTEGER DEFAULT nextval(seq)' },
    { sourceType: 'BIGINT AUTO_INCREMENT', targetType: 'BIGSERIAL' },
    { sourceType: 'TINYINT(1)', targetType: 'BOOLEAN', notes: 'PostgreSQL native BOOL' },
    { sourceType: 'TINYINT', targetType: 'SMALLINT' },
    { sourceType: 'DATETIME', targetType: 'TIMESTAMP', notes: 'PostgreSQL TIMESTAMP (no timezone)' },
    { sourceType: 'LONGTEXT / MEDIUMTEXT', targetType: 'TEXT', notes: 'No length limit in PostgreSQL' },
    { sourceType: 'JSON (10.2+)', targetType: 'JSONB', notes: 'JSONB is preferred; supports GIN indexing' },
    { sourceType: 'UUID (10.7+)', targetType: 'UUID', notes: 'Native UUID in both databases' },
    { sourceType: 'INET4 / INET6 (10.5+)', targetType: 'INET', notes: 'PostgreSQL INET type for IP addresses' },
    { sourceType: 'FLOAT', targetType: 'REAL' },
    { sourceType: 'DOUBLE / DOUBLE PRECISION', targetType: 'DOUBLE PRECISION' },
    { sourceType: 'DECIMAL(p,s)', targetType: 'NUMERIC(p,s)' },
    { sourceType: 'BLOB', targetType: 'BYTEA' },
    { sourceType: 'ENUM', targetType: "CREATE TYPE enum_name AS ENUM ('a','b')", notes: 'Define PostgreSQL ENUM type first' },
  ],

  'mariadb-to-mysql': [
    { sourceType: 'INT AUTO_INCREMENT', targetType: 'INT AUTO_INCREMENT', notes: 'Identical syntax' },
    { sourceType: 'JSON (10.2+)', targetType: 'JSON', notes: 'MySQL 5.7+; compatible syntax' },
    { sourceType: 'UUID (10.7+)', targetType: 'CHAR(36)', notes: 'MySQL has no native UUID type' },
    { sourceType: 'INET4 / INET6', targetType: 'VARCHAR(45)', notes: 'MySQL has no IP type; use VARCHAR' },
    { sourceType: 'ROW_NUMBER() OVER()', targetType: 'ROW_NUMBER() OVER()', notes: 'MySQL 8.0+ supports window functions' },
    { sourceType: 'SEQUENCE (10.3+)', targetType: 'AUTO_INCREMENT', notes: 'MySQL uses AUTO_INCREMENT not sequences' },
    { sourceType: 'Most other types', targetType: 'Same syntax', notes: 'MariaDB and MySQL are largely compatible' },
  ],

  'mariadb-to-sqlite': [
    { sourceType: 'INT AUTO_INCREMENT', targetType: 'INTEGER PRIMARY KEY' },
    { sourceType: 'BIGINT', targetType: 'INTEGER' },
    { sourceType: 'TINYINT(1)', targetType: 'INTEGER', notes: 'Store 0 or 1' },
    { sourceType: 'FLOAT / DOUBLE', targetType: 'REAL' },
    { sourceType: 'DECIMAL', targetType: 'NUMERIC' },
    { sourceType: 'VARCHAR / TEXT / LONGTEXT', targetType: 'TEXT' },
    { sourceType: 'DATETIME / TIMESTAMP', targetType: 'TEXT', notes: "ISO 8601 format" },
    { sourceType: 'BLOB', targetType: 'BLOB' },
    { sourceType: 'JSON (10.2+)', targetType: 'TEXT', notes: 'SQLite 3.38+ json_extract() on TEXT' },
    { sourceType: 'UUID (10.7+)', targetType: 'TEXT', notes: '36-char UUID string' },
    { sourceType: 'ENUM', targetType: 'TEXT', notes: 'Add CHECK constraint: CHECK(col IN (\'a\',\'b\'))' },
  ],

  'mariadb-to-sql-server': [
    { sourceType: 'INT AUTO_INCREMENT', targetType: 'INT IDENTITY(1,1)' },
    { sourceType: 'BIGINT AUTO_INCREMENT', targetType: 'BIGINT IDENTITY(1,1)' },
    { sourceType: 'TINYINT(1)', targetType: 'BIT' },
    { sourceType: 'DATETIME / TIMESTAMP', targetType: 'DATETIME2' },
    { sourceType: 'VARCHAR(n)', targetType: 'NVARCHAR(n)', notes: 'Use NVARCHAR for Unicode' },
    { sourceType: 'TEXT / LONGTEXT', targetType: 'NVARCHAR(MAX)' },
    { sourceType: 'JSON (10.2+)', targetType: 'NVARCHAR(MAX)', notes: 'SQL Server 2016+ JSON functions' },
    { sourceType: 'UUID (10.7+)', targetType: 'UNIQUEIDENTIFIER' },
    { sourceType: 'BLOB', targetType: 'VARBINARY(MAX)' },
    { sourceType: 'FLOAT', targetType: 'REAL' },
    { sourceType: 'DOUBLE', targetType: 'FLOAT' },
    { sourceType: 'DECIMAL(p,s)', targetType: 'DECIMAL(p,s)', notes: 'Same syntax' },
    { sourceType: 'ENUM', targetType: 'NVARCHAR(n)', notes: 'Add CHECK constraint' },
  ],
};

/**
 * Get the type mapping rows for a given route.
 * Returns undefined if no specific mapping exists for that route.
 */
export function getTypeMappings(category: 'convert' | 'generate', slug: string): TypeRow[] | undefined {
  if (category === 'generate') {
    return generateMappings[slug];
  }
  return convertMappings[slug];
}
